language: generic
sudo: false
before_install:
  - git submodule update --init --recursive
install:
  # source because it sets up env vars on some platforms
  - source ci/travis/travis_install.sh
script: ./run_tests.py
after_success:
  - codecov
env:
  global:
    # Travis can run out of RAM, so we need to be careful here.
    - COVERAGE=true
  matrix:
    - YCM_PYTHON_VERSION=2.7
    - YCM_PYTHON_VERSION=3.4
addons:
  apt:
    packages:
     # Everything below is a Python build dep (though it depends on Python
     # version). We need them because pyenv builds Python.
     - libssl-dev
     - zlib1g-dev
     - libbz2-dev
     - libreadline-dev
     - libsqlite3-dev
     - wget
     - curl
     - llvm
     - libncurses5-dev
     - libncursesw5-dev
cache:
  directories:
    - $HOME/.cache/pip  # Python packages from pip
    - $HOME/.pyenv  # pyenv
